# Generated by Django 5.1.3 on 2024-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(default=89, max_length=12),
            preserve_default=False,
        ),
    ]
